name: Stage 5 - Secrets Demo

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret safely
        run: echo "Secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
