name: Anatomy Test

on:
  push:

jobs:
  learning-job:
    name: Learning Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Greeting
        run: echo "Step 1 running"

      - name: Step 2 - Confirmation
        run: echo "Step 2 running"
